name: test 
on: 
  repository_dispatch:
    types: [build]
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: echo $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: print directory
        run : |
            pwd
            ls -a
            echo $GITHUB_WORKSPACE
