name: test 
on: push
jobs:
  print-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: print stuff
        run: echo "Hello world"
      - name: print directory
        run : |
            pwd
            ls -a
